/* main app logic */
const CONTACT_NUMBER = "6221110081";
function uid(){ return Math.random().toString(36).slice(2,9) + Date.now().toString(36).slice(-4) }
const nameEl = document.getElementById('name');
const saleIdEl = document.getElementById('saleId');
const phoneEl = document.getElementById('phone');
const productEl = document.getElementById('product');
const costEl = document.getElementById('cost');
const depositEl = document.getElementById('deposit');
const durationEl = document.getElementById('duration');
const locationEl = document.getElementById('location');
const boxEl = document.getElementById('box');
const bagEl = document.getElementById('bagColor');
const createBtn = document.getElementById('createBtn');
const clearBtn = document.getElementById('clearForm');
const listEl = document.getElementById('list');
const searchEl = document.getElementById('search');
const viewExpiredBtn = document.getElementById('viewExpired');
const installBtn = document.getElementById('installBtn');
let deferredPrompt = null;
window.addEventListener('beforeinstallprompt',(e)=>{e.preventDefault();deferredPrompt=e;installBtn.style.display='inline-block';});
installBtn.onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();const choice=await deferredPrompt.userChoice;deferredPrompt=null;installBtn.style.display='none';};
costEl.addEventListener('input',()=>{const cost=parseFloat((costEl.value||'0').replace(',', '.'))||0;const deposit=+(cost*0.30).toFixed(2);depositEl.value=deposit;});
createBtn.addEventListener('click',async()=>{const name=nameEl.value.trim();const saleId=saleIdEl.value.trim()||uid();const phone=phoneEl.value.trim();const product=productEl.value.trim();const cost=parseFloat((costEl.value||'0').replace(',', '.'))||0;const deposit=parseFloat((depositEl.value||'0').replace(',', '.'))||0;const duration=parseInt(durationEl.value||'15');const location=locationEl.value.trim();const box=boxEl.value.trim();const bag=bagEl.value.trim();if(!name||!product||cost<=0){alert('Nombre, producto y costo son obligatorios');return}const start=new Date();const due=new Date(start);due.setDate(due.getDate()+duration);const item={id:uid(),saleId,name,phone,product,productCost:cost,depositRequiredPercent:30,depositTaken:deposit,startDate:start.toISOString(),durationDays:duration,dueDate:due.toISOString(),location,boxNumber:box,bagColor:bag,payments:[],status:'active'};await dbAdd(item);renderList();clearForm();});
clearBtn.addEventListener('click',clearForm);searchEl.addEventListener('input',()=>renderList(false));viewExpiredBtn.addEventListener('click',()=>renderList(true));
function clearForm(){[nameEl,saleIdEl,phoneEl,productEl,costEl,depositEl,locationEl,boxEl,bagEl].forEach(i=>i.value='');durationEl.value='15';}
function computePaid(item){const payments=item.payments||[];const totalPayments=payments.reduce((s,p)=>s+(p.amount||0),0);return (item.depositTaken||0)+totalPayments;}
function computeRemaining(item){return Math.max(0,(item.productCost||0)-computePaid(item));}
async function renderList(showExpired=false){listEl.innerHTML='';const q=(searchEl.value||'').toLowerCase();const all=await dbGetAll();const now=new Date();const filtered=all.filter(i=>{const isExpired=new Date(i.dueDate)<now;if(showExpired&& !isExpired) return false;if(!showExpired&& isExpired) return false;if(!q) return true;return [i.name,i.saleId,i.phone,i.location,i.boxNumber,i.bagColor,i.product].some(f=>(f||'').toString().toLowerCase().includes(q));});filtered.sort((a,b)=>new Date(b.startDate)-new Date(a.startDate));filtered.forEach(i=>{const tpl=document.getElementById('itemTpl').content.cloneNode(true);tpl.querySelector('.item-title').textContent=i.name+' • '+i.product;const due=new Date(i.dueDate);tpl.querySelector('.item-sub').textContent=`Venta: ${i.saleId} • Tel: ${i.phone} • Vence: ${due.toLocaleDateString()}`;const rem=computeRemaining(i);const amountEl=tpl.querySelector('.item-amount');amountEl.textContent='$'+rem.toFixed(2);if(new Date(i.dueDate)<new Date()){const badge=document.createElement('span');badge.className='badge';badge.textContent='VENCIDO';tpl.querySelector('.item-left').appendChild(badge);}const editBtn=tpl.querySelector('.edit');const payBtn=tpl.querySelector('.pay');const ticketBtn=tpl.querySelector('.ticket');const smsBtn=tpl.querySelector('.sms');const waBtn=tpl.querySelector('.wa');const cancelBtn=tpl.querySelector('.cancel');editBtn.onclick=()=>editItem(i.id);payBtn.onclick=()=>addPaymentPrompt(i.id);ticketBtn.onclick=()=>shareTicket(i.id);smsBtn.onclick=()=>sendSMS(i.id);waBtn.onclick=()=>sendWhatsApp(i.id);cancelBtn.onclick=()=>{if(confirm('Cancelar apartado?')){cancelItem(i.id)}};listEl.appendChild(tpl);});}
async function editItem(id){const it=(await dbGetAll()).find(x=>x.id===id);if(!it)return;const name=prompt('Nombre',it.name);if(name===null)return;it.name=name;const product=prompt('Producto',it.product);if(product===null)return;it.product=product;const cost=parseFloat(prompt('Costo',it.productCost));if(isNaN(cost))return;it.productCost=cost;it.location=prompt('Lugar',it.location||'')||'';it.boxNumber=prompt('Número de caja',it.boxNumber||'')||'';it.bagColor=prompt('Color de la bolsa',it.bagColor||'')||'';await dbPut(it);renderList();}
async function addPaymentPrompt(id){const all=await dbGetAll();const it=all.find(x=>x.id===id);if(!it)return;const val=prompt('Monto de abono (número)');if(!val)return;const amt=parseFloat(val.replace(',', '.'));if(isNaN(amt)||amt<=0)return alert('Monto inválido');it.payments=it.payments||[];it.payments.push({id:uid(),date:new Date().toISOString(),amount:amt});await dbPut(it);alert('Abono agregado');renderList();}
async function cancelItem(id){const it=(await dbGetAll()).find(x=>x.id===id);if(!it)return;it.status='cancelled';await dbPut(it);renderList();}
async function shareTicket(id){const it=(await dbGetAll()).find(x=>x.id===id);if(!it)return;const paid=computePaid(it).toFixed(2);const remaining=computeRemaining(it).toFixed(2);const due=new Date(it.dueDate);let text=`Ernesto's Bazar - APARTADO\nCliente: ${it.name}\nVenta: ${it.saleId}\nTel: ${it.phone}\nProducto: ${it.product}\nCosto: $${it.productCost.toFixed(2)}\nPagado: $${paid}\nRestante: $${remaining}\nVence: ${due.toLocaleDateString()}\nLugar: ${it.location} • Caja: ${it.boxNumber}\nBolsa: ${it.bagColor}\n\nTenga en cuenta: Apartados normales 15 días; en mueble 30 días.\nContacto: ${CONTACT_NUMBER}\nGracias por su preferencia.`;try{const { jsPDF }=window.jspdf;const doc=new jsPDF({unit:'pt',format:[300,400]});doc.setFontSize(14);doc.text("Ernesto's Bazar",20,30);doc.setFontSize(11);const lines=doc.splitTextToSize(text,260);doc.text(lines,20,60);const blob=doc.output('blob');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${it.saleId}_ticket.pdf`;a.click();URL.revokeObjectURL(url);}catch(e){navigator.clipboard.writeText(text).then(()=>alert('Texto del ticket copiado al portapapeles'));}}
function sendSMS(id){dbGetAll().then(all=>{const it=all.find(x=>x.id===id);if(!it)return;const text=encodeURIComponent(`Ernesto's Bazar - APARTADO\nCliente: ${it.name}\nVenta: ${it.saleId}\nProducto: ${it.product}\nRestante: $${computeRemaining(it).toFixed(2)}\nContacto: ${CONTACT_NUMBER}`);window.location.href=`sms:${it.phone}?&body=${text}`;});}
function sendWhatsApp(id){dbGetAll().then(all=>{const it=all.find(x=>x.id===id);if(!it)return;const text=encodeURIComponent(`Ernesto's Bazar - APARTADO\nCliente: ${it.name}\nVenta: ${it.saleId}\nProducto: ${it.product}\nRestante: $${computeRemaining(it).toFixed(2)}\nContacto: ${CONTACT_NUMBER}`);window.open(`https://wa.me/?text=${text}`,'_blank');});}
if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{});}
renderList();